'use client';
import {useState,useRef,useEffect} from 'react';
import {flushSync} from 'react-dom';
import {Keyboard,ArrowUp,ArrowLeft,Mic,Square,Star,Plus,Minus,ArrowUpRight,Volume2,Shirt,CloudRain,Sun} from 'lucide-react';
import {products,money,rating,type Product} from '@/lib/catalog';
import {initial,transition,context,search,suitability,focusedReviews,focusedAttributes,comparison,tool,type State,type View} from '@/lib/commerce';
import TryOn from './try-on';
import {LiveToolBatches,screenContextEvents} from '@/lib/gpt-live';
function path(s:State){if(s.view==='home')return '/';if(s.view==='search'||s.view==='compare')return '/'+s.view;return `/product/${s.active}${s.view==='product'?'':'/'+s.view}${s.topic?'?topic='+encodeURIComponent(s.topic):''}`;}
function fromUrl():State {const parts=location.pathname.split('/').filter(Boolean),topic=new URLSearchParams(location.search).get('topic')||'';if(parts[0]==='product'&&products.some(p=>p.id===parts[1]))return {...initial,active:parts[1],view:((['intro','reviews','attributes','tryon'].includes(parts[2])?parts[2]:'product') as View),topic};if(parts[0]==='search'||parts[0]==='compare'){const s=transition(initial,{view:'search'}).state;return {...s,view:parts[0],ids:parts[0]==='compare'?s.ids.slice(0,4):s.ids};}return initial;}
export default function Surface(){
 const [state,setState]=useState<State>(initial),[answer,setAnswer]=useState(''),[heard,setHeard]=useState(''),[text,setText]=useState(''),[error,setError]=useState(''),[working,setWorking]=useState(false),[status,setStatus]=useState<'off'|'connecting'|'listening'|'thinking'|'speaking'>('off'),[muted,setMuted]=useState(false),[audioBlocked,setAudioBlocked]=useState(false);
 const [typing,setTyping]=useState(false);
 const motionVersion=useRef(0);
 const activeTransition=useRef<{skipTransition:()=>void}|null>(null);
 const current=useRef(state),peer=useRef<RTCPeerConnection|null>(null),channel=useRef<RTCDataChannel|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),generation=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null),asking=useRef(false);
 current.current=state;
 function send(v:unknown){if(channel.current?.readyState==='open')channel.current.send(JSON.stringify(v));}
 function sync(s:State){screenContextEvents(s).forEach(send);}
 function update(s:State,push=true){
 const previous=current.current,changed=JSON.stringify(previous)!==JSON.stringify(s);
 const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const commit=()=>{current.current=s;setState(s);if(push)history.pushState(s,'',path(s));setError('');if(changed)window.scrollTo({top:0,behavior:'instant'});};
 activeTransition.current?.skipTransition();
 const motion=++motionVersion.current;
 document.documentElement.classList.remove('carousel-next','carousel-previous');
 const swap=previous.active&&s.active&&previous.active!==s.active&&['product','intro','reviews','attributes'].includes(previous.view)&&['product','intro','reviews','attributes'].includes(s.view);
 if(swap&&!reduce){
 const direction=previous.ids.indexOf(s.active!)<previous.ids.indexOf(previous.active!)?'previous':'next';
 const sign=direction==='next'?1:-1;
 if(typeof document.startViewTransition==='function'){
 document.documentElement.classList.add('carousel-'+direction);
 const vt=document.startViewTransition(()=>flushSync(commit));activeTransition.current=vt;
 void vt.ready.catch(()=>{});void vt.finished.finally(()=>{if(motionVersion.current===motion)document.documentElement.classList.remove('carousel-next','carousel-previous');});
 }else{
 const old=document.querySelector<HTMLElement>('.stage'),rect=old?.getBoundingClientRect(),clone=old?.cloneNode(true) as HTMLElement|undefined;
 if(clone&&rect){clone.setAttribute('aria-hidden','true');clone.inert=true;Object.assign(clone.style,{position:'fixed',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',margin:'0',zIndex:'20',pointerEvents:'none'});document.body.appendChild(clone);}
 flushSync(commit);
 const frames=[{transform:'translateX('+sign*70+'px)',opacity:0},{transform:'translateX(0)',opacity:1}];
 document.querySelector('.stage')?.animate(frames,{duration:650,easing:'cubic-bezier(.22,1,.36,1)'});
 if(clone){const exit=clone.animate([{transform:'translateX(0)',opacity:1},{transform:'translateX('+(-sign*100)+'px)',opacity:0}],{duration:500,easing:'cubic-bezier(.22,1,.36,1)'});void exit.finished.finally(()=>clone.remove());}
 }return;
 }
 if(changed&&!reduce&&previous.view==='home'&&s.view==='search'){
 const origin=document.querySelector('.orb')?.getBoundingClientRect();flushSync(commit);
 if(origin){const orb=document.querySelector<HTMLElement>('.orb'),end=orb?.getBoundingClientRect();if(orb&&end)orb.animate([{transform:'translate('+(origin.left+origin.width/2-end.left-end.width/2)+'px,'+(origin.top+origin.height/2-end.top-end.height/2)+'px) scale('+(origin.width/end.width)+')'},{transform:'translate(0,0) scale(1)'}],{duration:900,easing:'cubic-bezier(.22,1,.36,1)'});}
 if(origin)document.querySelectorAll<HTMLElement>('.product-card').forEach((card,i)=>{const rect=card.getBoundingClientRect();card.animate([{opacity:0,transform:'translate('+(origin.left+origin.width/2-rect.left-rect.width/2)+'px,'+(origin.top+origin.height/2-rect.top-rect.height/2)+'px) scale(.06)',filter:'blur(8px)'},{opacity:1,transform:'translate(0,0) scale(1)',filter:'blur(0)'}],{duration:760,delay:i*85,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'});});
 }else if(changed&&!reduce&&typeof document.startViewTransition==='function'){
 const vt=document.startViewTransition(()=>flushSync(commit));activeTransition.current=vt;void vt.ready.catch(()=>{});
 }else if(changed&&!reduce){
 const stage=document.querySelector<HTMLElement>('.stage');
 const leaving=stage?.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-10px)'}],{duration:180,easing:'ease-in'});
 current.current=s;
 const enter=()=>{flushSync(commit);document.querySelector('.stage')?.animate([{opacity:0,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}],{duration:520,easing:'cubic-bezier(.22,1,.36,1)'});};
 if(leaving)void leaving.finished.then(enter).catch(()=>{});else commit();
 }else commit();
 }
 function act(a:unknown){try{const r=transition(current.current,a);update(r.state);sync(r.state);setAnswer('');return r.data;}catch(e){setError(e instanceof Error?e.message:'Please try again.');}}
 function cleanup(){generation.current++;if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;const pc=peer.current;peer.current=null;channel.current=null;pc?.close();if(audio.current)audio.current.srcObject=null;setStatus('off');}
 function stop(){send({type:'session.close'});cleanup();}
 useEffect(()=>{update(fromUrl(),false);const pop=()=>{const s=history.state?.view?history.state:fromUrl();update(s,false);sync(s);};window.addEventListener('popstate',pop);return()=>{window.removeEventListener('popstate',pop);cleanup();};},[]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(mc.registerTool({name:'show_commerce_surface',description:tool.description,inputSchema:tool.parameters,annotations:{readOnlyHint:false},execute:async(a:unknown)=>{const r=transition(current.current,a);update(r.state);sync(r.state);return r.data;}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 async function ask(message:string){if(asking.current||!message.trim())return;setText('');setHeard(message);setAnswer('');setError('');asking.current=true;setWorking(true);
 try{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,state:current.current})});const body=await r.json() as any;if(!r.ok)throw Error(body.error);update(body.state);sync(body.state);setAnswer(body.answer);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{asking.current=false;setWorking(false);}}
 async function start(){if(peer.current||status!=='off')return;setError('');setStatus('connecting');const token=++generation.current;
 try{if(!navigator.mediaDevices?.getUserMedia)throw Error('This browser cannot use the microphone. You can type below.');const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(token!==generation.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const pc=new RTCPeerConnection();peer.current=pc;media.getTracks().forEach(t=>pc.addTrack(t,media));pc.ontrack=e=>{if(audio.current){audio.current.srcObject=e.streams[0]||new MediaStream([e.track]);void audio.current.play().catch(()=>setAudioBlocked(true));}};
 const dc=pc.createDataChannel('oai-events');channel.current=dc;const batches=new LiveToolBatches();let speaking='';dc.onmessage=e=>{if(token!==generation.current)return;try{const event=JSON.parse(e.data);if(event.type==='session.started'){if(timer.current)clearTimeout(timer.current);setStatus('listening');sync(current.current);}if(event.type==='session.closed'){cleanup();return;}if(event.type==='session.delegation.created')setStatus('thinking');if(event.type==='session.input_transcript.delta'){setStatus('listening');setHeard(old=>speaking==='user'?old+event.delta:event.delta);speaking='user';}if(event.type==='session.output_transcript.delta'){setStatus('speaking');setAnswer(old=>speaking==='assistant'?old+event.delta:event.delta);speaking='assistant';}
 const calls=batches.receive(event);for(const call of calls){let output:unknown;try{if(call.name==='stop_listening'){stop();return;}const result=transition(current.current,JSON.parse(call.arguments));update(result.state);output=result.data;}catch(err){output={error:err instanceof Error?err.message:'Invalid request'};}send({type:'response.item.create',item:{type:'function_call_output',call_id:call.call_id,output:JSON.stringify(output)}});}if(calls.length)send({type:'response.create',event_id:crypto.randomUUID()});if(event.type==='error'){cleanup();setError('The voice connection encountered a problem. Tap the orb to reconnect.');}}catch{setError('Please try that again.');}};
 pc.onconnectionstatechange=()=>{if(token===generation.current&&['failed','disconnected'].includes(pc.connectionState)){cleanup();setError('Connection lost. Tap the orb to continue from this screen.');}};timer.current=setTimeout(()=>{if(token===generation.current){cleanup();setError('Connection timed out. Please try again.');}},30000);
 const offer=await pc.createOffer();await pc.setLocalDescription(offer);const r=await fetch('/api/realtime',{method:'POST',headers:{'Content-Type':'application/sdp'},body:offer.sdp});const data=await r.json() as any;if(token!==generation.current)return;if(!r.ok)throw Error(data.error);await pc.setRemoteDescription({type:'answer',sdp:data.transport.sdp});
 }catch(e){if(token===generation.current){cleanup();setError(e instanceof Error?e.message:'Could not start voice.');}}}
 const p=products.find(x=>x.id===state.active),visible=state.ids.map(id=>products.find(x=>x.id===id)!).filter(Boolean),reviews=p?focusedReviews(p,state.topic):[],total=search(state.filters).length;
 const cues=state.view==='search'?(visible.length?[...(visible.length>1?[{label:'Compare the first two',prompt:'Compare the first and second displayed products for my needs.'}]:[]),{label:`Tell me about the ${visible[0].brand} one`,prompt:`Open the product ${visible[0].name}, ID ${visible[0].id}, and show its details.`}]:[{label:'Show me more options',prompt:'Relax my budget and show more options, keeping my category and color.'}]):state.view==='product'||state.view==='intro'?[{label:'What are customers saying?',prompt:'What are customers saying about this product?'},{label:'What should I look out for?',prompt:'Show all customer reviews and their concerns for this product, with no topic filter.'},{label:'What will I look like in this?',prompt:'Show me wearing this product.'}]:state.view==='reviews'?[{label:'Anyone mention the quality?',prompt:'Show reviews specifically about quality.'},{label:'What about the fit?',prompt:'Show reviews about sizing and fit.'}]:state.view==='attributes'?[{label:'How do I care for it?',prompt:'Show the care and washing instructions.'},{label:'Does it fit my needs?',prompt:'Compare this with alternatives for my stated needs.'}]:state.view==='compare'?[{label:'Which suits me best?',prompt:'Open the best option for my stated needs and show its introduction.'},{label:'Show the trade-offs',prompt:'Compare the drawbacks of these products for my stated needs.'}]:state.view==='tryon'?[{label:'Back to the product',prompt:'Go back to the product details.'},{label:'What are customers saying?',prompt:'Show customer reviews for this product.'}]:[];
 const nav=(view:View,topic='')=>act({view,topic});
 const productImage=(item:Product,className='')=><span role="img" aria-label={item.name} className={'product-visual '+className} style={{viewTransitionName:'image-'+item.id,backgroundImage:`url(${item.image})`,backgroundSize:item.imagePosition?'600% 800%':'cover',backgroundPosition:item.imagePosition||'center'}}/>;
 const ratingText=(item:Product)=><span className="rating" style={{viewTransitionName:'rating-'+item.id}}><Star size={14} fill="currentColor"/>{rating(item).toFixed(1)} <small>({item.reviews.length})</small></span>;
 return <div className={`surface-app view-${state.view}`}><audio ref={audio} autoPlay muted={muted}/>{!['home','search'].includes(state.view)&&<header className="site-top"><button className="brand" onClick={()=>nav('home')}>surface<span>®</span></button><span className="demo-label">A DECISIONOS CONCEPT</span><a href="https://decisionos.me/case-studies.html">The thinking <ArrowUpRight size={15}/></a></header>}
 <main className="stage" key={state.view+state.active+state.topic+state.ids.join('')}><div className={'scene-light scene-'+state.view} aria-hidden="true"><i/><i/><i/></div>
 {state.view==='home'?<section className="home-stage" aria-label="Voice shopping"/>:<>
 {state.view!=='search'&&<div className="context-line"><button onClick={()=>nav('search')}><ArrowLeft size={16}/>Your finds</button><span>{state.need||'A little closer to what you need'}</span></div>}
 {state.view==='search'&&<section><div className="product-grid">{visible.map((item,i)=><button className="product-card" key={item.id} onClick={()=>act({view:'product',productId:item.id})}><div className="product-photo">{productImage(item)}<span className="product-number">0{i+1}</span></div><div className="card-line"><small>{item.brand}</small>{ratingText(item)}</div><h2 style={{viewTransitionName:'title-'+item.id}}>{item.name}</h2>{suitability(item,state.need).reason&&<p className="match-reason">{suitability(item,state.need).reason}</p>}<div className="card-line"><span>{money(item.price)}</span><small>{item.ageMin}–{item.ageMax} years</small></div></button>)}</div>{!visible.length&&<p className="empty-results">No matches yet. Try a different color or budget.</p>}</section>}
 {p&&state.view==='tryon'&&<TryOn product={p} onBack={()=>nav('product')}/>}
 {p&&['product','intro','reviews','attributes'].includes(state.view)&&<>
 {['product','intro'].includes(state.view)?<section className="product-focus"><div className="focus-photo">{productImage(p)}</div><div className="focus-copy"><p className="eyebrow">{p.brand}</p><h1 style={{viewTransitionName:'title-'+p.id}}>{p.name}</h1><div className="focus-price">{money(p.price)} {ratingText(p)}</div>{suitability(p,state.need).reason&&<p className="match-reason">{suitability(p,state.need).reason}</p>}{state.view==='intro'&&<div className="intro-summary"><p>{p.intro}</p><ul><li>{p.attributes.Material}</li><li>{p.attributes.Fit} fit · {p.attributes['Sizes available']}</li><li>{p.reviews[0].likes}</li></ul><p className="tradeoff">Worth knowing: {p.reviews[1].concern}.</p></div>}</div></section>:<>
 <button className="mini-product" onClick={()=>nav('product')}>{productImage(p)}<span><span style={{viewTransitionName:'title-'+p.id,display:'block'}}>{p.name}</span><small>{money(p.price)} · {p.brand}</small></span></button>
 {state.view==='reviews'&&<section className="review-focus"><div className="section-intro"><p className="eyebrow">{state.topic?'LET’S LOOK AT '+state.topic.toUpperCase():'THE PEOPLE’S PERSPECTIVE'}</p><h1>{state.topic?`What they say about ${state.topic}.`:'Loved for this. Less so for that.'}</h1></div><div className="review-overview"><div className="rating-big"><strong style={{viewTransitionName:'rating-'+p.id}}>{rating(p).toFixed(1)}</strong><span>out of 5 · {p.reviews.length} sample reviews</span><div>{[5,4,3,2,1].map(n=><div className="rating-bar" key={n}><span>{n}</span><i><b style={{width:`${p.reviews.filter(r=>r.rating===n).length/p.reviews.length*100}%`}}/></i></div>)}</div></div><div className="sentiment"><h2><Plus size={18}/> What people like</h2>{[...new Set(reviews.map(r=>r.likes).filter(Boolean))].slice(0,3).map(t=><p key={t}>{t}</p>)}</div><div className="sentiment negative"><h2><Minus size={18}/> What gives them pause</h2>{[...new Set(reviews.map(r=>r.concern).filter(Boolean))].slice(0,3).map(t=><p key={t}>{t}</p>)}</div></div><div className="topic-chips">{['','quality','fabric','fit','washing'].map(t=><button aria-pressed={state.topic===t} key={t} onClick={()=>nav('reviews',t)}>{t||'All reviews'}</button>)}</div>{!reviews.length?<p>No sample reviews address that topic. Try fabric, fit, or washing.</p>:<div className="review-quotes">{reviews.slice(0,3).map(r=><article key={r.id}><span className="rating"><Star size={14} fill="currentColor"/>{r.rating}/5</span><h3>{r.title}</h3><blockquote>“{r.text}”</blockquote><small>{r.name} · Sample review</small></article>)}</div>}</section>}
 {state.view==='attributes'&&<section className="attribute-focus"><div className="section-intro"><p className="eyebrow">THE DETAILS YOU ASKED FOR</p><h1>{state.topic?`Let’s talk ${state.topic}.`:'The fabric. The fit. The practical bits.'}</h1></div><dl>{focusedAttributes(p,state.topic).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{focusedAttributes(p,state.topic).length===0&&<p>That detail isn’t available in the sample catalog. <button onClick={()=>nav('attributes')}>Show all attributes</button></p>}</section>}
 </>}
 </>}
 {state.view==='compare'&&<section className="comparison-focus"><div className="section-intro"><p className="eyebrow">BETTER FOR YOU, NOT JUST BETTER</p><h1>A different kind of “best”.</h1><p>{state.need||'For everyday comfort and value.'}</p><small>Fit scores use equal weight for: {state.priorities.join(', ')||'comfort, value'}. Illustrative assessment, not customer ratings.</small></div><div className="compare-grid">{visible.map(p=>({p,c:comparison(p,state.priorities)})).sort((a,b)=>b.c.score-a.c.score).map(({p,c},i)=><article key={p.id}><span className="compare-rank">{i===0?'Closest fit':'Another way to go'}</span><button className="compare-photo" onClick={()=>act({view:'product',productId:p.id})}>{productImage(p)}</button><h2 style={{viewTransitionName:'title-'+p.id}}>{p.name}</h2><div className="card-line">{money(p.price)}{ratingText(p)}</div><div className="fit-score"><strong>{c.score}</strong><span>/100<br/>for your needs</span></div><h3>Why it works</h3><p>{c.good.length?c.good.join(' · '):'No standout strength for these priorities.'}</p><h3>The trade-off</h3><p>{c.bad.length?c.bad.join(' · '):p.reviews[1].concern}</p><small>{p.reviews[1].concern}</small><button className="text-link" onClick={()=>act({view:'product',productId:p.id})}>Look closer <ArrowUpRight size={15}/></button></article>)}</div></section>}
 {state.view!=='search'&&<p className="sample-footer">Sample catalog, imagery, reviews, and fit assessments. No checkout or real seller.</p>}
 </>}
 {cues.length>0&&<aside className="conversation-cues" aria-label="Suggested questions"><span>You can ask</span><div>{cues.map(cue=><button key={cue.label} disabled={working} onClick={()=>ask(cue.prompt)}>“{cue.label}” <ArrowUpRight size={13}/></button>)}</div></aside>}
 </main>
 <aside className={`voice-dock ${state.view==='home'?'home-dock':''} ${typing?'is-typing':''}`} aria-label="Conversation controls"><div className="voice-text" aria-live="polite">{state.view==='home'&&!error?<><p className="home-heading">Tell us what<br/>you’re looking for.</p><div className="home-examples" aria-label="Example requests"><span className="examples-label">Examples</span>{[{label:'For sport',text:'Find me red sports T-shirts',icon:Shirt,tone:'sport'},{label:'For the kids',text:'Show me jackets for kids',icon:CloudRain,tone:'kids'},{label:'For every day',text:'Comfortable jeans under €40',icon:Sun,tone:'everyday'}].map(({label,text:prompt,icon:Icon,tone})=><button key={tone} className="home-prompt" disabled={working} onClick={()=>void ask(prompt)}><span className={'prompt-icon '+tone}><Icon size={18} aria-hidden="true"/></span><span className="prompt-copy"><span className="prompt-label">{label}</span><span>{prompt}</span></span><ArrowUpRight className="prompt-arrow" size={16} aria-hidden="true"/></button>)}</div></>:error?<p className="error">{error}</p>:working?<p>Finding the answer…</p>:answer?<p>{answer}</p>:<p>{status==='off'?'Tap the orb. Tell me what you need.':status==='connecting'?'Connecting…':status==='thinking'?'Finding the answer…':status==='speaking'?'Keep talking whenever you’re ready.':'I’m listening. Keep going.'}</p>}{heard&&state.view!=='home'&&state.view!=='search'&&<small>You: {heard}</small>}</div><div className="dock-controls">{state.view==='home'&&<div className="sparkles" aria-hidden="true">{Array.from({length:32},(_,i)=><i key={i} style={{'--i':i,'--radius':(90+(i%5)*18)+'px','--duration':(9+i%7)+'s'} as React.CSSProperties}/>)}</div>}<button className={`orb ${status}`} onClick={status==='off'?start:stop} aria-label={status==='off'?'Start live shopping':'Stop live shopping'}><span className="orb-core"/><span className="orb-mist"/><span className="orb-glint"/>{status==='off'?<Mic size={23}/>:<Square size={18}/>}</button>{!['home','search'].includes(state.view)&&<button className="keyboard-toggle" aria-label={typing?'Hide keyboard':'Type instead'} aria-expanded={typing} onClick={()=>setTyping(!typing)}><Keyboard size={21}/></button>}{typing&&!['home','search'].includes(state.view)&&<form onSubmit={e=>{e.preventDefault();void ask(text);}}><input autoFocus aria-label="Ask Surface" placeholder="Or type a thought…" value={text} onChange={e=>setText(e.target.value)}/><button aria-label="Send" disabled={working||!text.trim()}><ArrowUp size={20}/></button></form>}{status!=='off'&&!['home','search'].includes(state.view)&&<button className="audio-toggle" aria-label={muted?'Unmute answers':'Mute answers'} aria-pressed={muted} onClick={()=>setMuted(!muted)}><Volume2 size={19}/>{muted&&<span/>}</button>}</div>{audioBlocked&&<button onClick={()=>{void audio.current?.play();setAudioBlocked(false);}}>Enable spoken answers</button>}</aside>
 </div>;
}
