export type Review = { id:string; name:string; rating:number; title:string; text:string; topics:string[]; likes:string; concern:string };
export type Product = { id:string; name:string; brand:string; category:string;color:string; price:number; image:string;imagePosition:string; ageMin:number; ageMax:number; sleeve:string; intro:string; attributes:Record<string,string>; scores:Record<string,number>; reviews:Review[] };
export const colors=["red", "blue", "green", "black", "white", "pink", "yellow", "purple"];
const styles={"tshirts": [["Levi\u2019s", "Graphic cotton tee", 18, "Cotton jersey", "Regular", "Soft all-day cotton comfort", "Print may fade after frequent washing"], ["adidas", "Shoulder-stripe sports tee", 28, "Recycled polyester stretch jersey", "Athletic", "Dries quickly after active play", "Feels less soft than cotton"], ["Zara", "Daisy-print relaxed tee", 23, "Cotton elastane jersey", "Relaxed", "Playful print and roomy movement", "Runs wide on smaller frames"], ["H&M", "Striped cotton tee", 10, "Cotton jersey", "Regular", "Lightweight comfort at a low price", "May shrink in a hot wash"], ["Next", "Pocket crew tee", 16, "Cotton jersey", "Regular", "Useful chest pocket and sturdy seams", "Pocket adds weight on hot days"], ["Uniqlo", "Contrast raglan tee", 20, "Cotton blend jersey", "Easy", "Flexible sleeves and smooth fabric", "Slightly longer body than expected"]], "jeans": [["Levi\u2019s", "Straight-leg jeans", 45, "Cotton denim", "Straight", "Durable denim and useful pockets", "Denim feels stiff before the first wash"], ["Zara", "Wide-leg jeans", 32, "Cotton denim", "Wide leg", "Roomy legs make movement easy", "Hem may need shortening"], ["H&M", "Stretch skinny jeans", 22, "Cotton elastane denim", "Skinny", "Stretch waist stays comfortable", "Narrow legs can feel snug"], ["Next", "Cargo-pocket jeans", 38, "Cotton denim", "Cargo", "Large pockets are practical", "Extra pockets add bulk"], ["Gap", "Relaxed tapered jeans", 40, "Cotton stretch denim", "Tapered", "Relaxed thighs with a tidy ankle", "Waist runs slightly large"], ["Mango", "Carpenter jeans", 36, "Cotton denim", "Carpenter", "Reinforced seams handle busy days", "Heavier denim takes longer to dry"]], "jackets": [["Uniqlo", "Quilted puffer jacket", 55, "Polyester shell with synthetic fill", "Regular", "Warm padding without much weight", "Too warm for mild afternoons"], ["adidas", "Hooded rain jacket", 48, "Water-resistant recycled polyester", "Regular", "Hood and shell handle light showers", "Not designed for prolonged heavy rain"], ["Levi\u2019s", "Denim trucker jacket", 60, "Cotton denim", "Regular", "Strong seams and timeless styling", "Unlined denim offers limited warmth"], ["Zara", "Varsity bomber jacket", 42, "Polyester cotton blend", "Relaxed", "Soft ribbed cuffs and a roomy cut", "Bulky beneath another coat"], ["H&M", "Fleece zip jacket", 25, "Polyester fleece", "Regular", "Soft warm fleece at a low price", "Wind passes through the fleece"], ["Next", "Utility pocket jacket", 50, "Cotton canvas", "Easy", "Useful pockets and durable canvas", "Canvas needs time to soften"]]};
export const products:Product[]=Object.entries(styles).flatMap(([category,options])=>colors.flatMap((color,row)=>options.map(([brand,label,base,material,fit,like,concern],column)=>{
 const id=category==='tshirts'&&row===0?`tee-${column+1}-1`:`${category}-${row+1}-${column+1}`;
 const price=Number(base)+(row%3)*2;
 const isJeans=category==='jeans',isJacket=category==='jackets';
 const attributes:Record<string,string>={Material:String(material),Fit:String(fit),Color:color,'Sizes available':'6–14 years',Care:'Machine wash at 30°C; follow care label',Returns:'30-day illustrative return policy',Origin:'Illustrative branded concept; generated imagery, prices and reviews; no real seller'};
 if(isJeans)Object.assign(attributes,{'Size 10 waist':'64 cm','Size 10 inside leg':'62 cm',Rise:'Mid rise',Closure:'Button and zip',Pockets:'Front and back pockets'});
 else Object.assign(attributes,{Sleeves:isJacket?'Long sleeves':'Short sleeves','Size 10 chest':isJacket?'82 cm':'72 cm','Size 10 length':isJacket?'56 cm':'51 cm',...(isJacket?{Lining:column===0?'Synthetic insulation':column===4?'Fleece':'Lightweight or unlined',Season:column===0?'Autumn / winter':'Spring / autumn'}:{'Fabric weight':column===1?'130 gsm':'160 gsm'})});
 const likes=String(like),tradeoff=String(concern);
 return {id,category,name:`${brand} ${label} · ${color}`,brand:String(brand),color,price,image:category==='tshirts'&&row===0&&column<4?'/products/'+['levis','adidas','zara','hm'][column]+'.png':`/products/${category}-sheet.png`,imagePosition:category==='tshirts'&&row===0&&column<4?'':`${column*20}% ${row*100/7}%`,ageMin:6,ageMax:14,sleeve:isJeans?'':isJacket?'long':'short',intro:`${label} in ${color}, with a ${String(fit).toLowerCase()} fit. ${likes}.`,attributes,scores:{comfort:column===1?7:9,durability:column===0?9:7,value:Math.max(5,10-Math.floor(price/15)),breathability:isJacket?6:8,style:column===2?10:8},reviews:[
 {id:id+'-a',name:'Maya',rating:5,title:'Comfortable for everyday use',text:`Bought these for my ten-year-old. ${likes}. The ${color} looks lovely.`,topics:['comfort','fabric','quality','fit'],likes,concern:''},
 {id:id+'-b',name:'Alex',rating:4,title:'Good, with a small trade-off',text:`The stitching is tidy. ${tradeoff}. Check the care instructions.`,topics:['quality','fabric','washing','durability'],likes:'Tidy stitching and a pleasing color',concern:tradeoff},
 {id:id+'-c',name:'Sam',rating:column%2?4:5,title:'Check the size guide',text:`The ${String(fit).toLowerCase()} fit works well for us. Compare measurements before choosing an age size.`,topics:['fit','size','comfort'],likes:'Comfortable for school and weekends',concern:'Check measurements before choosing a size'},
 {id:id+'-d',name:'Jordan',rating:3,title:'A useful wardrobe option',text:`At €${price}, this is ${price<30?'an accessible everyday option':'more of a considered purchase'}. ${tradeoff}.`,topics:['value','quality','washing'],likes:price<30?'Accessible everyday price':'Useful wardrobe staple',concern:tradeoff}
 ]};
})));
export const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
export const rating=(p:Product)=>p.reviews.reduce((s,r)=>s+r.rating,0)/p.reviews.length;
