import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import ts from 'typescript';import assert from 'node:assert/strict';import WebSocket from 'ws';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'surface-check-'));
for(const name of ['catalog','commerce','gpt-live']){const source=fs.readFileSync(`lib/${name}.ts`,'utf8').replace(/from '(\.\/[^']+)'/g,"from '$1.mjs'");fs.writeFileSync(`${dir}/${name}.mjs`,ts.transpileModule(source,{compilerOptions:{target:99,module:99}}).outputText);}
const {initial,transition,focusedReviews,comparison,suitability,search}=await import(`${dir}/commerce.mjs`);const {products}=await import(`${dir}/catalog.mjs`);
let state=transition(initial,{view:'search',filters:{color:'red',age:10,sleeve:'short'},need:'Red short-sleeve tees for a ten-year-old, everyday comfort and value'}).state;assert.equal(state.ids.length,4);assert.equal(new Set(state.ids.slice(0,4).map(id=>id.split('-')[1])).size,4);assert.equal(transition(initial,{view:'search',filters:{color:'orange'}}).state.ids.length,0);assert.throws(()=>transition(state,{view:'product',productId:'fake'}));assert(focusedReviews(products[0],'quality').every(r=>r.topics.includes('quality')));assert(comparison(products[3],['value']).score>comparison(products[1],['value']).score);console.log('PASS filters, diverse results, invalid IDs, review focus, needs scoring');
assert.equal(products.length,144);
for(const category of ['tshirts','jeans','jackets'])for(const color of ['red','blue','green','black','white','pink','yellow','purple']){
 const matches=products.filter(p=>p.category===category&&p.color===color);assert.equal(matches.length,6);assert.equal(new Set(matches.map(p=>p.image+p.imagePosition)).size,6);assert(matches.every(p=>p.reviews.length===4));
 const first=transition(initial,{view:'search',filters:{category,color}}).state;assert.equal(first.ids.length,4);assert(first.ids.every(id=>matches.some(p=>p.id===id)));
 const more=transition(first,{view:'search',filters:{offset:4}}).state;assert.equal(more.ids.length,2);assert(more.ids.every(id=>!first.ids.includes(id)));
}
const switched=transition(state,{view:'search',filters:{category:'jackets',color:'blue'}}).state;assert.equal(switched.filters.sleeve,'');assert(switched.ids.every(id=>products.find(p=>p.id===id).category==='jackets'));
console.log('PASS 144 products, 24 color/category groups, distinct options, pagination and category switching');
const opened=transition(state,{view:'product',productId:state.ids[0]}).state;
const neighbour=transition(opened,{view:'product',direction:'next'}).state;
assert.equal(neighbour.active,state.ids[1]);assert.equal(transition(neighbour,{view:'product',direction:'previous'}).state.active,state.ids[0]);assert.throws(()=>transition(opened,{view:'product',direction:'previous'}));
assert.throws(()=>transition({...opened,active:state.ids.at(-1)},{view:'product',direction:'next'}));
console.log('PASS next/previous product navigation and boundaries');
const sporting=transition(initial,{view:'search',need:'good for sports',filters:{category:'tshirts',color:'red'}}).state;
assert.match(products.find(p=>p.id===sporting.ids[0]).name,/adidas/);
assert.match(suitability(products.find(p=>p.id===sporting.ids[0]),sporting.need).reason,/Quick-drying/);
assert.equal(suitability(products[0],'red tee for age ten').reason,'');
assert.match(suitability(products.find(p=>p.category==='jeans'),'sports').reason,/restrictive/);
console.log('PASS purpose ranking, card reasons, trade-offs, and attribute-only requests');
assert.equal(transition(opened,{view:'tryon'}).state.active,opened.active);assert.throws(()=>transition(initial,{view:'tryon'}));
for(const query of ['red t shirts','red T-shirts','red t‑shirts','show me some red t shirts'])assert.equal(search({...initial.filters,query}).length,6);
assert.equal(search({...initial.filters,category:'T-shirts',color:' Red ',sleeve:'short sleeves'}).length,6);
const stale={...initial,filters:{...initial.filters,category:'jackets',color:'pink',age:40,maxPrice:1,offset:20}};
assert.equal(transition(stale,{view:'search',resetFilters:true,filters:{category:'tshirts',color:'red'}}).state.ids.length,4);
assert.equal(search({...initial.filters,category:'tshirts',color:'orange'}).length,0);
console.log('PASS natural T-shirt spellings, sleeve aliases and fresh searches after stale filters');
assert.equal(transition(initial,{view:'search',direction:'next',productId:'stale',filters:{category:'tshirts',color:'red'}}).state.ids.length,4);
if(!process.argv.includes('--live')){fs.rmSync(dir,{recursive:true});process.exit(0);}
const {liveSession,LiveToolBatches,screenContextEvents}=await import(`${dir}/gpt-live.mjs`);const key=fs.readFileSync('.dev.vars','utf8').match(/^OPENAI_API_KEY=(.+)$/m)[1].trim().replace(/^["']|["']$/g,'');state=initial;
const tasks=[['Find red short sleeve t-shirts for a ten-year-old girl, for everyday comfort and value.','search'],['Open the first one.','product'],['Give me an introduction.','intro'],['What do people say about it?','reviews'],['Has anybody spoken about fabric quality?','reviews'],['Show me its material and sizing attributes.','attributes'],['Which is better for me? Compare four from the search for everyday comfort and value.','compare']];
if(process.argv.includes('--currency'))tasks.splice(1);
if(process.argv.includes('--red'))tasks.splice(0,tasks.length,['Show me red t-shirts.','search']);
if(process.argv.includes('--catalog'))tasks.splice(0,tasks.length,['Find blue jeans for a ten-year-old.','search'],['Show the other blue jeans.','search'],['Now show pink jackets instead.','search']);
await new Promise((resolve,reject)=>{const ws=new WebSocket('wss://api.openai.com/v1/live/sessions',{headers:{Authorization:`Bearer ${key}`}});const batches=new LiveToolBatches();let index=0,spoken='',chunks=0,final=false,timer,settle,silence,closed=false;const send=o=>ws.send(JSON.stringify(o));const fail=e=>{clearTimeout(timer);clearTimeout(settle);clearInterval(silence);ws.close();reject(e);};const ask=()=>{screenContextEvents(state).forEach(send);spoken='';chunks=0;final=false;timer=setTimeout(()=>fail(Error('Timeout '+tasks[index][0]+' '+spoken)),45000);send({type:'response.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text:tasks[index][0]}]}});send({type:'response.create'});};const check=()=>{try{assert.equal(state.view,tasks[index][1]);if(process.argv.includes('--red')){assert.equal(state.ids.length,4);assert(state.ids.every(id=>products.find(p=>p.id===id).color==='red'));}assert(chunks>0);if(process.argv.includes('--catalog')){assert.equal(state.filters.category,index===2?'jackets':'jeans');assert.equal(state.filters.color,index===2?'pink':'blue');if(index===1)assert.equal(state.ids.length,2);}if(process.argv.includes('--currency'))assert(!/dollar/i.test(spoken),'Currency must be euros');if(index===4)assert(/quality|fabric/.test(state.topic));if(index===6)assert(state.ids.length>=3);console.log('PASS LIVE',index+1,state.view,spoken);clearTimeout(timer);if(++index<tasks.length)ask();else{send({type:'session.close'});timer=setTimeout(()=>fail(Error('No close')),5000);}}catch(e){fail(e);}};
ws.on('open',()=>send({type:'session.start',session:{...liveSession,audio:{...liveSession.audio,format:{type:'audio/pcm',rate:24000}}}}));ws.on('error',fail);ws.on('message',raw=>{try{const e=JSON.parse(raw);if(e.type==='error')throw Error(JSON.stringify(e));if(e.type==='session.started'){silence=setInterval(()=>{if(ws.readyState===1)send({type:'session.input_audio.append',audio:Buffer.alloc(960).toString('base64')});},20);ask();}if(e.type==='session.output_audio.delta')chunks++;if(e.type==='session.output_transcript.delta'){spoken+=e.delta;clearTimeout(settle);settle=setTimeout(()=>{if(final&&spoken.length>10)check();},2500);}const calls=batches.receive(e);for(const call of calls){const changed=transition(state,JSON.parse(call.arguments));state=changed.state;send({type:'response.item.create',item:{type:'function_call_output',call_id:call.call_id,output:JSON.stringify(changed.data)}});}if(e.type==='response.event'&&e.event.type==='response.completed'&&!calls.length)final=true;if(calls.length)send({type:'response.create'});if(e.type==='session.closed'){closed=true;clearTimeout(timer);clearTimeout(settle);clearInterval(silence);ws.close();resolve();}}catch(e){fail(e);}});ws.on('close',()=>{if(!closed)fail(Error('Unexpected close'));});});fs.rmSync(dir,{recursive:true});
